import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/NavBar";
import Footer from "./Footer";

import { CookieConsentProvider } from "@/app/context/CookieConsentContext";
import CookieBanner from "@/app/components/cookies/CookieBanner";
import GoogleTags from "@/app/components/analytics/GoogleTags";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CookieConsentProvider>
          <GoogleTags />
          <NavBar />
          <main>{children}</main>
          <Footer />
          <CookieBanner />
        </CookieConsentProvider>
      </body>
    </html>
  );
}
